// generated by file-router
/* eslint-disable */
import { lazy } from "react"

export type Routes = "paint-worklet" | "other" | "lightning" | "fifou"

export type RouteMeta = {
	title: string
}

export type Route = {
	Component: React.LazyExoticComponent<() => JSX.Element>
	meta: RouteMeta
}

export const ROUTES = {
	"paint-worklet": {
		Component: lazy(() => import("./pages/paint-worklet/index.tsx")),
		meta: {
			title: 'Paint Worklet'
		},
	},
	"other": {
		Component: lazy(() => import("./pages/other/index.tsx")),
		meta: {
			title: 'Other'
		},
	},
	"lightning": {
		Component: lazy(() => import("./pages/lightning/index.tsx")),
		meta: {
			title: 'Lightning'
		},
	},
	"fifou": {
		Component: lazy(() => import("./pages/fifou/index.tsx")),
		meta: {
			title: 'Fifou'
		},
	}
} as const satisfies Record<Routes, Route>
